#服务端口
server:
  port: 1148

#服务注册中心
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:1127/eureka/

#服务名称
spring:
  application:
    name: api-config-center
  cloud:
    #配置中心
    config:
      server:
        git:
          #服务的git仓库地址
          uri: http://gitlab.miduchina.com/wrd/config-center.git
          #配置文件所在的目录
          search-paths: /**
          username: shuanglong
          password: shuanglong
      #配置文件所在的分支
      label: master
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#    virtual-host: /
#spring 2.X actuator
#http://ip:port/actuator/refresh
management:
  endpoints:
    web:
      exposure:
        include: "*"